from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
FRONTEND = ROOT / "frontend"
sys.path.insert(0, str(BACKEND))


def require(condition: bool, label: str) -> None:
    if not condition:
        raise AssertionError(label)
    print(f"[PASS] {label}")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


app = read(FRONTEND / "src" / "App.jsx")
styles = read(FRONTEND / "src" / "styles.css")
routes = read(BACKEND / "app" / "api" / "routes.py")
port_service = read(BACKEND / "app" / "services" / "port_service.py")
db_design = read(BACKEND / "app" / "services" / "database_schema_design.py")
db_provision = read(BACKEND / "app" / "services" / "generated_database_provision_service.py")
main = read(BACKEND / "app" / "main.py")
codex = read(BACKEND / "app" / "services" / "codex_app_server_service.py")

checks = [
    ("AGENTSTUDIO_FRONTEND_VERSION='5.460'" in app, "Frontend version 5.460"),
    ('version="5.460"' in main, "FastAPI version 5.460"),
    ('AGENTSTUDIO_CODEX_CLIENT_VERSION = "5.460"' in codex, "Codex client version 5.460"),
    ('"version": "5.460"' in routes, "Route health version 5.460"),
    ("function AgentRuntimeSetupPanel" in app, "New Agent runtime setup UI"),
    ("function AgentGenerationFinalPreview" in app, "Final Agent generation preview UI"),
    ("추천값 적용" in app and "사용 가능 PORT 다시 검색" in app and "USER_FIXED" in app, "Port recommend/apply/recheck/USER_FIXED UX"),
    ("/agent-runtime/ports/recommend" in app and '@router.post("/agent-runtime/ports/recommend")' in routes, "Generated Agent port recommendation API"),
    ("runtime_ports.generated.json" in routes and "runtime_ports.generated.json" in port_service, "Shared generated runtime config persistence"),
    ("agentstudio_project_in_use" in port_service and "agent_internal_conflict" in port_service and "os_in_use" in port_service, "Port collision states"),
    ("실행 직전 PORT 재검사" in port_service, "Pre-launch port recheck"),
    ("PostgreSQL" in app and "Firestore" in app and "Redis" in app and "agent-db-provider-tabs" in app, "Database provider tabs"),
    ("DB Resource Plan / DB 생성 계획 Preview" in app, "DB Resource Plan Preview"),
    ("테이블 자동 생성 공통 정책" in app and "agent-table-policy-preview" in app, "CRUD table policy Preview UI"),
    ("created_at" in app and "updated_at" in app and "is_deleted" in app and "created_by" in app and "updated_by" in app, "Editable common relational columns"),
    ("def apply_common_table_policy" in db_design and "def apply_common_table_policy_overrides" in db_design, "Common relational table policy engine"),
    ("BIGINT GENERATED BY DEFAULT AS IDENTITY" in db_design, "PostgreSQL IDENTITY default"),
    ("agentstudio_set_updated_at" in db_design, "Shared updated_at trigger function"),
    ("WHERE is_deleted = FALSE" in db_design, "Soft-delete partial unique index"),
    ("table_policy_overrides" in db_provision and "apply_common_table_policy_overrides" in db_provision, "Preview table overrides applied to provisioning"),
    ("Agent 생성 최종 확인" in app and "개발 계획" in app and "실행 환경" in app and "Database" in app, "Unified final Preview content"),
    ("databasePlanApproved" in app and "runtimeSetupApproved" in app, "Project creation approval gates"),
    ("/* ===== v5.460 New Agent Runtime + Database Provisioning Preview UX ===== */" in styles, "v5.460 UX styles"),
]

for cond, label in checks:
    require(cond, label)

# Behavioral checks for the table policy.
from app.services.database_schema_design import (  # noqa: E402
    apply_common_table_policy,
    apply_common_table_policy_overrides,
    generate_postgresql_ddl,
)
from app.services.port_service import (  # noqa: E402
    recommend_generated_agent_ports,
    resolve_generated_agent_runtime_setup,
)

sample = {
    "enabled": True,
    "modules": [],
    "tables": [
        {
            "name": "customers",
            "module": "CUSTOM",
            "purpose": "고객 업무 데이터",
            "source": "llm_custom_business",
            "crud": ["C", "R", "U", "D"],
            "columns": [
                {"name": "email", "type": "VARCHAR(255)", "nullable": False, "primary_key": False, "unique": True, "default": "", "references": ""}
            ],
            "indexes": [],
        },
        {
            "name": "agent_execution_logs",
            "module": "OBSERVABILITY",
            "purpose": "실행 로그",
            "source": "llm_custom_business",
            "crud": ["C", "R"],
            "columns": [
                {"name": "message", "type": "TEXT", "nullable": False, "primary_key": False, "unique": False, "default": "", "references": ""}
            ],
            "indexes": [],
        },
    ],
}
policy = apply_common_table_policy(sample)
customer_cols = {row["name"] for row in policy["tables"][0]["columns"]}
log_cols = {row["name"] for row in policy["tables"][1]["columns"]}
require({"id", "created_at", "updated_at", "is_deleted", "created_by", "updated_by"}.issubset(customer_cols), "CRUD C/R/U/D common columns")
require(log_cols == {"id", "message"}, "Append-only C/R table excludes update/delete audit columns")
fixed = apply_common_table_policy_overrides(policy, {"customers": {"is_deleted": False, "created_by": False, "updated_by": False}})
fixed_cols = {row["name"] for row in fixed["tables"][0]["columns"]}
require("is_deleted" not in fixed_cols and "created_by" not in fixed_cols and "updated_by" not in fixed_cols, "USER_FIXED Preview override behavior")
ddl = generate_postgresql_ddl(policy)
require("GENERATED BY DEFAULT AS IDENTITY" in ddl and "agentstudio_set_updated_at" in ddl and "WHERE is_deleted = FALSE" in ddl, "Generated PostgreSQL DDL policy")

ports = recommend_generated_agent_ports(
    frontend_technology="React + Vite",
    backend_technology="FastAPI",
    frontend_port=5173,
    backend_port=8000,
    api_share_backend=True,
    reserved_ports=[5173, 8000],
)
require(ports["frontend"]["recommended"] != 5173 and ports["backend"]["recommended"] != 8000, "Reserved AgentStudio ports are avoided")
fixed_runtime = {
    "mode": "CONFIGURE",
    "auto_allocate": False,
    "approved": True,
    "frontend": {"technology": "React + Vite", "host": "localhost", "port": 5173, "user_fixed": True},
    "backend": {"technology": "FastAPI", "host": "localhost", "port": 8000, "user_fixed": False},
    "api": {"share_backend": True, "host": "localhost", "port": 8000, "base_path": "/api/v1", "user_fixed": False},
}
conflict = resolve_generated_agent_runtime_setup(fixed_runtime, reserved_ports=[5173])
require(not conflict["ok"] and bool(conflict.get("errors")), "USER_FIXED collision is never silently reassigned")

print(f"v5.460 contract: {len(checks) + 6}/{len(checks) + 6} PASS")
